### ISSUE TITLE
Memory and Training Speed Computation

### ISSUE THREAD

**Issue by xiyuanzh** [tianzhou2011/FiLM#1]
Hi, thanks for your great work! Would it be possible to share the script to calculate the memory usage and training speed presented in Figure 9? Thanks a lot!

**Comment by tianzhou2011** [comment]
we calculated memory and training speed based on the univariate
experiments. You can simply run the univariate scripts. Per epoch time
should be printed out during training. And we log the memory during the
experiment by " nvidia-smi ". It is worth mentioning that the running time
will increase significantly for multivariate experiments with many
variables.
