### ISSUE TITLE
ValueError during testing 

### ISSUE THREAD

**Issue by Niharikajo** [tianzhou2011/FiLM#2]
Hello Zhou,

Thank you for releasing the code.
I am trying to recreate your results

I was able to run and recreate the results for the Film model.

Now, I am trying to run the Informer and Logformer models for comparison
I am able to train successfully
  
But, during testing, I am getting the following error

`ValueError: operands could not be broadcast together with shapes (44,96,1) (1408,96,1) `

Please let me know the fix for this, thanks.

Best regards
Niharika

**Comment by tianzhou2011** [comment]
Actually, i didn't run the baselines, they were implemented for studying only, i forgot to remove them..... The baseline results in FiLM are cited from autoformer paper [https://github.com/thuml/Autoformer]. If you want to repeat those results, please check there. 
Tian

**Comment by 962155704** [comment]
> Hello Zhou,
> 
> Thank you for releasing the code. I am trying to recreate your results
> 
> I was able to run and recreate the results for the Film model.
> 
> Now, I am trying to run the Informer and Logformer models for comparison I am able to train successfully
> 
> But, during testing, I am getting the following error
> 
> `ValueError: operands could not be broadcast together with shapes (44,96,1) (1408,96,1) `
> 
> Please let me know the fix for this, thanks.
> 
> Best regards Niharika

Excuse me, I met the same mistake as you. How did you solve this problem?
