### ISSUE TITLE
FiLM consult 

### ISSUE THREAD

**Issue by endeavoryg** [tianzhou2011/FiLM#3]
Hello, I am a graduate student at China University of Geosciences Wuhan, and I recently read your paper FiLM: Frequency improved Legendre Memory Model for Long-term Time Series Forecasting published in NIPS and open-sourced the code. In the paper, it is written that FLIM is a feature extraction model that can be used to extract historical information and remove historical noise. After reading your paper, I ran the open source FILM.py file, which contains examples for testing, and I encountered a problem that the output of the model is all one value.

**Comment by tianzhou2011** [comment]
Read the readme first.  I am not sure i understand your question. if you want to run film on the datasets in the paper, you should just run the scripts in the script folder.
