### ISSUE TITLE
FEL Original version

### ISSUE THREAD

**Issue by sujing863** [tianzhou2011/FiLM#6]
In your paper, you wrote about Frequency Enhanced Layer Original version (use weights W). Where is the source of it?

**Comment by tianzhou2011** [comment]
![image](https://github.com/tianzhou2011/FiLM/assets/7770939/166b8678-6815-4465-b7e8-7d54c2a57712)

**Comment by sujing863** [comment]
I am very sorry that I expressed myself wrongly. What I would like to know is who came up with the methodology for the original version of FEL, e.g. a particular paper or book.

**Comment by tianzhou2011** [comment]
https://arxiv.org/abs/2010.08895
